package com.flexcore.dto_hibernate;
// Generated Nov 17, 2014 12:34:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name="moneda"
    ,catalog="flexcore"
)
public class Moneda  implements java.io.Serializable {


     private int idMoneda;
     private String descripcion;
     private Set cuentaahorrovistas = new HashSet(0);

    public Moneda() {
    }

	
    public Moneda(int idMoneda) {
        this.idMoneda = idMoneda;
    }
    public Moneda(int idMoneda, String descripcion, Set cuentaahorrovistas) {
       this.idMoneda = idMoneda;
       this.descripcion = descripcion;
       this.cuentaahorrovistas = cuentaahorrovistas;
    }
   
     @Id 

    
    @Column(name="idMoneda", unique=true, nullable=false)
    public int getIdMoneda() {
        return this.idMoneda;
    }
    
    public void setIdMoneda(int idMoneda) {
        this.idMoneda = idMoneda;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="moneda")
    public Set<Cuentaahorrovista> getCuentaahorrovistas() {
        return this.cuentaahorrovistas;
    }
    
    public void setCuentaahorrovistas(Set cuentaahorrovistas) {
        this.cuentaahorrovistas = cuentaahorrovistas;
    }




}


