package com.flexcore.dto_hibernate;
// Generated Nov 17, 2014 12:34:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Personasbeneficiarias generated by hbm2java
 */
@Entity
@Table(name="personasbeneficiarias"
    ,catalog="flexcore"
)
public class Personasbeneficiarias  implements java.io.Serializable {


     private int idPersona;
     private String nombre;
     private Set cuentas = new HashSet(0);

    public Personasbeneficiarias() {
    }

	
    public Personasbeneficiarias(int idPersona, String nombre) {
        this.idPersona = idPersona;
        this.nombre = nombre;
    }
    public Personasbeneficiarias(int idPersona, String nombre, Set cuentas) {
       this.idPersona = idPersona;
       this.nombre = nombre;
       this.cuentas = cuentas;
    }
   
     @Id 

    
    @Column(name="idPersona", unique=true, nullable=false)
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="relacionbenefeciariascuenta", catalog="flexcore", joinColumns = { 
        @JoinColumn(name="idPersona", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="numCuenta", nullable=false, updatable=false) })
    public Set<Cuenta> getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


