package com.flexcore.dto_hibernate;
// Generated Nov 17, 2014 12:34:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Tipostiempo generated by hbm2java
 */
@Entity(name="tipostiempo")
@XmlRootElement
@Table(name="tipostiempo"
    ,catalog="flexcore"
)
public class Tipostiempo  implements java.io.Serializable {


     private int idTiempo;
     private String Descripcion;
     private Set<Cuentaahorroautomatico> cuentaahorroautomaticos = new HashSet(0);

    public Tipostiempo() {
    }

	
    public Tipostiempo(int idTiempo) {
        this.idTiempo = idTiempo;
    }
    public Tipostiempo(int idTiempo, String descripcion, Set cuentaahorroautomaticos) {
       this.idTiempo = idTiempo;
       this.Descripcion = descripcion;
       this.cuentaahorroautomaticos = cuentaahorroautomaticos;
    }
   
     @Id 

    
    @Column(name="idTiempo", unique=true, nullable=false)
    @XmlElement
    public int getIdTiempo() {
        return this.idTiempo;
    }
    
    public void setIdTiempo(int idTiempo) {
        this.idTiempo = idTiempo;
    }

    
    @Column(name="descripcion", length=45)
    @XmlElement
    public String getDescripcion() {
        return this.Descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.Descripcion = descripcion;
    }

    @XmlTransient
    @OneToMany(fetch=FetchType.LAZY, mappedBy="tipostiempo")
    public Set<Cuentaahorroautomatico> getCuentaahorroautomaticos() {
        return this.cuentaahorroautomaticos;
    }
    
    public void setCuentaahorroautomaticos(Set cuentaahorroautomaticos) {
        this.cuentaahorroautomaticos = cuentaahorroautomaticos;
    }




}


