package com.flexcore.dto_hibernate;
// Generated Nov 17, 2014 12:34:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipomovimiento generated by hbm2java
 */
@Entity
@Table(name="tipomovimiento"
    ,catalog="flexcore"
)
public class Tipomovimiento  implements java.io.Serializable {


     private int idtipoMovimiento;
     private String descripcion;
     private Set historicotransaccionals = new HashSet(0);
     private Set transaccionesvuelos = new HashSet(0);

    public Tipomovimiento() {
    }

	
    public Tipomovimiento(int idtipoMovimiento, String descripcion) {
        this.idtipoMovimiento = idtipoMovimiento;
        this.descripcion = descripcion;
    }
    public Tipomovimiento(int idtipoMovimiento, String descripcion, Set historicotransaccionals, Set transaccionesvuelos) {
       this.idtipoMovimiento = idtipoMovimiento;
       this.descripcion = descripcion;
       this.historicotransaccionals = historicotransaccionals;
       this.transaccionesvuelos = transaccionesvuelos;
    }
   
     @Id 

    
    @Column(name="idtipoMovimiento", unique=true, nullable=false)
    public int getIdtipoMovimiento() {
        return this.idtipoMovimiento;
    }
    
    public void setIdtipoMovimiento(int idtipoMovimiento) {
        this.idtipoMovimiento = idtipoMovimiento;
    }

    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipomovimiento")
    public Set<Historicotransaccional> getHistoricotransaccionals() {
        return this.historicotransaccionals;
    }
    
    public void setHistoricotransaccionals(Set historicotransaccionals) {
        this.historicotransaccionals = historicotransaccionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipomovimiento")
    public Set<Transaccionesvuelo> getTransaccionesvuelos() {
        return this.transaccionesvuelos;
    }
    
    public void setTransaccionesvuelos(Set transaccionesvuelos) {
        this.transaccionesvuelos = transaccionesvuelos;
    }




}


