package com.flexcore.dto_hibernate;
// Generated Nov 17, 2014 12:34:42 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cuentaahorrovista generated by hbm2java
 */
@Entity
@Table(name="cuentaahorrovista"
    ,catalog="flexcore"
)
public class Cuentaahorrovista  implements java.io.Serializable {


     private Integer numCuenta;
     private Cuenta cuenta;
     private Moneda moneda;
     private String descripcion;

    public Cuentaahorrovista() {
    }

	
    public Cuentaahorrovista(Cuenta cuenta, Moneda moneda) {
        this.cuenta = cuenta;
        this.moneda = moneda;
    }
    public Cuentaahorrovista(Cuenta cuenta, Moneda moneda, String descripcion) {
       this.cuenta = cuenta;
       this.moneda = moneda;
       this.descripcion = descripcion;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="cuenta"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="numCuenta", unique=true, nullable=false)
    public Integer getNumCuenta() {
        return this.numCuenta;
    }
    
    public void setNumCuenta(Integer numCuenta) {
        this.numCuenta = numCuenta;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipoMoneda", nullable=false)
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


