package com.flexcore.dto_hibernate;
// Generated Nov 17, 2014 12:34:42 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Retiros generated by hbm2java
 */
@Entity
@Table(name="retiros"
    ,catalog="flexcore"
)
public class Retiros  implements java.io.Serializable {


     private Integer idRetiro;
     private Cuenta cuenta;
     private BigDecimal monto;
     private Date fecha;

    public Retiros() {
    }

    public Retiros(Cuenta cuenta, BigDecimal monto, Date fecha) {
       this.cuenta = cuenta;
       this.monto = monto;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRetiro", unique=true, nullable=false)
    public Integer getIdRetiro() {
        return this.idRetiro;
    }
    
    public void setIdRetiro(Integer idRetiro) {
        this.idRetiro = idRetiro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCuenta", nullable=false)
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }

    
    @Column(name="monto", nullable=false, precision=15)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


